"""empty message

Revision ID: 06589d6d791c
Revises: 690990304c9e
Create Date: 2022-02-21 23:10:36.846525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06589d6d791c'
down_revision = '690990304c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('office_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'offices', ['office_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'office_id')
    # ### end Alembic commands ###
