"""empty message

Revision ID: 14d40e72e875
Revises: c01213d7727e
Create Date: 2022-02-16 00:55:35.320607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d40e72e875'
down_revision = 'c01213d7727e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacations', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacations', sa.Column('state', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
