"""empty message

Revision ID: 3e69b96ff91e
Revises: 8f15aa37623c
Create Date: 2022-02-16 02:14:48.798776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e69b96ff91e'
down_revision = '8f15aa37623c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_approve_vacation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_approve_vacation')
    # ### end Alembic commands ###
