"""empty message

Revision ID: 496e73fb7702
Revises: 06589d6d791c
Create Date: 2022-03-02 22:35:13.565196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496e73fb7702'
down_revision = '06589d6d791c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacation_used',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'year')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacation_used')
    # ### end Alembic commands ###
