"""empty message

Revision ID: 690990304c9e
Revises: f67cae1e7651
Create Date: 2022-02-21 22:16:01.819211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690990304c9e'
down_revision = 'f67cae1e7651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offices')
    # ### end Alembic commands ###
