"""empty message

Revision ID: 8f15aa37623c
Revises: 14d40e72e875
Create Date: 2022-02-16 00:56:09.159460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f15aa37623c'
down_revision = '14d40e72e875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacations', sa.Column('state', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacations', 'state')
    # ### end Alembic commands ###
