"""empty message

Revision ID: be03012d28b1
Revises: 496e73fb7702
Create Date: 2022-03-17 19:42:44.362501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be03012d28b1'
down_revision = '496e73fb7702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacation_used', 'days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('vacations', sa.Column('is_mailing', sa.Boolean(), nullable=True))
    op.add_column('vacations', sa.Column('mailing_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacations', 'mailing_comment')
    op.drop_column('vacations', 'is_mailing')
    op.alter_column('vacation_used', 'days',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
