"""empty message

Revision ID: c01213d7727e
Revises: db5ac3346470
Create Date: 2022-02-16 00:42:57.457263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01213d7727e'
down_revision = 'db5ac3346470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vacations', 'responsible_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacations', 'responsible_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vacations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
