"""empty message

Revision ID: db5ac3346470
Revises: ae0055796601
Create Date: 2022-02-15 22:32:18.432291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5ac3346470'
down_revision = 'ae0055796601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacations', sa.Column('date_delta', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacations', 'date_delta')
    # ### end Alembic commands ###
